# Generated by Django 4.2.7 on 2023-11-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news_user_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='news',
            field=models.ManyToManyField(related_name='likes', to='app.news'),
        ),
    ]
