# Generated by Django 4.2.7 on 2023-11-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_news_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default='link', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='news',
            field=models.ManyToManyField(to='app.news'),
        ),
    ]
