# Generated by Django 4.2.7 on 2023-11-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_news_number_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='news',
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(related_name='liked_news', through='app.UserLikes', to='app.user'),
        ),
    ]
