# Generated by Django 4.2.7 on 2023-11-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_userlikes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='description', max_length=150),
        ),
    ]
