# Generated by Django 4.2.7 on 2024-01-13 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikes',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
